openapi: 3.0.0
info:
  title: FE1T Documentation
  version: "0.1"
servers:
  - url: "https://mxp-public-fe1t-app-api.dev.icadsistemi.com/v1"
    description: Development
  - url: "https://mxp-public-fe1t-app-api.prod.icadsistemi.com/v1"
    description: Production
paths:
  "/configuration":
    get:
      tags:
        - Configuration
      summary: Get app first configuration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/ConfigurationOutput"
  "/customers":
    get:
      tags:
        - Customers
      summary: Search customer
      parameters:
        - name: vat_number
          in: query
          description: VAT number
          required: false
          schema:
            type: string
        - name: fiscal_code
          in: query
          description: Fiscal code
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/CustomersOutput"
  "/customers/{id}":
    put:
      tags:
        - Customers
      summary: Update customer
      parameters:
        - name: id
          in: path
          description: Customer id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/CustomersInput"
      responses:
        "201":
          description: No content
  "/fuelstations":
    get:
      tags:
        - Fuelstations
      summary: Get users enabled fuelstations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/FuelstationsOutput"
  "/fuelstations/{fuelstation_id}":
    get:
      tags:
        - Fuelstations
      summary: Get fuelstation settings
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/FuelstationsSettingsOutput"
    put:
      tags:
        - Fuelstations
      summary: Update fuelstation settings
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/FuelstationSettingsInput"
      responses:
        "201":
          description: No content
  "/fuelstations/{fuelstation_id}/prices":
    get:
      tags:
        - Prices
      summary: Get fuelstation active prices
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/PricesOutput"
    put:
      tags:
        - Prices
      summary: Upsert fuelstation price
      parameters:
        - name: id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./schemas.yaml#/components/schemas/PricesInput"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/PricesOutput"
  "/invoices":
    get:
      tags:
        - Invoices
      summary: Search invoices
      parameters:
        - name: fuelstation_id
          in: query
          description: Fuelstation id
          required: false
          schema:
            type: integer
        - name: status
          in: query
          description: Invoice status
          required: false
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/InvoicesSearchOutput"
  "/invoices/{invoice_id}/details":
    get:
      tags:
        - Invoices
      summary: Get invoice details
      parameters:
        - name: invoice_id
          in: path
          description: Invoice id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./schemas.yaml#/components/schemas/InvoiceDetailsOutput"
  "/invoices/{invoice_id}/details/{detail_id}":
    put:
      tags:
        - Invoices
      summary: Update invoice detail
      parameters:
        - name: invoice_id
          in: path
          description: Invoice id
          required: true
          schema:
            type: integer
        - name: detail_id
          in: path
          description: Detail id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "schemas.yaml#/components/schemas/InvoiceDetailInput"
      responses:
        "201":
          description: No content
