openapi: 3.0.0
info:
  title: Fe1T Documentation
  version: "0.1"
servers:
  - url: "https://mxp-public-fe1t-app-api.dev.icadsistemi.com/v1"
    description: Development
  - url: "https://mxp-public-fe1t-app-api.prod.icadsistemi.com/v1"
    description: Production
paths:
  "/configuration":
    get:
      tags:
        - Configuration
      summary: Get app first configuration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Configuration"
  "/fuelstations":
    get:
      tags:
        - Fuelstations
      summary: Get users enabled fuelstations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fuelstations"
  "/fuelstations/{id}":
    get:
      tags:
        - Fuelstations
      summary: Get fuelstation settings
      parameters:
        - name: id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fuelstations settings output"
  "/fuelstations/{id}/prices":
    get:
      tags:
        - Prices
      summary: Get fuelstation active prices
      parameters:
        - name: id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fuelstations prices output"
    put:
      tags:
        - Prices
      summary: Upsert fuelstation price
      parameters:
        - name: id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fuelstations price input"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fuelstations prices output"
components:
  schemas:
    Configuration:
      type: object
      properties:
        articles:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
        price_levels:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
        fuelstations_settings:
          type: object
          properties:
            unattended_photo_values:
              type: array
              items:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        payment_periodicities:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
    Fuelstations:
      type: object
      properties:
        fuelstations:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
              address:
                type: string
              city:
                type: string
    Fuelstations prices output:
      type: object
      properties:
        prices:
          type: array
          items:
            properties:
              service_level:
                type: integer
              product_code:
                type: string
              price:
                type: number
    Fuelstations price input:
      type: object
      properties:
        service_level:
          type: integer
        product_code:
          type: string
        price:
          type: number
    Fuelstations settings output:
      type: object
      properties:
        settings:
          type: object
          properties:
            attended:
              type: object
              properties:
                auto_approval:
                  type: boolean
                is_ticket_mandatory:
                  type: boolean
                is_picture_mandatory:
                  type: boolean
                supply_auto_retrieve:
                  type: boolean
            unattended:
              type: object
              properties:
                auto_approval:
                  type: boolean
                is_ticket_mandatory:
                  type: boolean
                is_picture_mandatory:
                  type: enum
                  enum:
                    - "1"
                    - "2"
                    - "3"
            pumps:
              type: integer
            articles:
              type: array
              items:
                properties:
                  code:
                    string: integer
                  name:
                    type: string
