openapi: 3.0.0
info:
  title: FE1T Documentation
  version: '0.1'
servers:
  - url: 'https://mxp-public-fe1t-app-api.dev.icadsistemi.com/v1'
    description: Development
  - url: 'https://mxp-public-fe1t-app-api.prod.icadsistemi.com/v1'
    description: Production
paths:
  /configuration:
    get:
      tags:
        - Configuration
      summary: Get app first configuration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ConfigurationOutput'
  /customers:
    get:
      tags:
        - Customers
      summary: Search customer
      parameters:
        - name: vat_number
          in: query
          description: VAT number
          required: false
          schema:
            type: string
        - name: fiscal_code
          in: query
          description: Fiscal code
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/CustomersOutput'
  '/customers/{id}':
    put:
      tags:
        - Customers
      summary: Update customer
      parameters:
        - name: id
          in: path
          description: Customer id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/CustomersInput'
      responses:
        '201':
          description: No content
  /fuelstations:
    get:
      tags:
        - Fuelstations
      summary: Get users enabled fuelstations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/FuelstationsOutput'
  '/fuelstations/{fuelstation_id}/prices':
    get:
      tags:
        - Prices
      summary: Get fuelstation active prices
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/PricesOutput'
    put:
      tags:
        - Prices
      summary: Upsert fuelstation price
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/PricesInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/PricesOutput'
  '/fuelstations/{fuelstation_id}':
    get:
      tags:
        - Fuelstations
      summary: Get fuelstation settings
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/FuelstationsSettingsOutput'
    put:
      tags:
        - Fuelstations
      summary: Update fuelstation settings
      parameters:
        - name: fuelstation_id
          in: path
          description: Fuelstation id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/FuelstationSettingsInput'
      responses:
        '201':
          description: No content
  /invoices:
    get:
      tags:
        - Invoices
      summary: Search invoices
      parameters:
        - name: fuelstation_id
          in: query
          description: Fuelstation id
          required: false
          schema:
            type: integer
        - name: status
          in: query
          description: Invoice status
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/InvoicesSearchOutput'
  '/invoices/{invoice_id}/details':
    get:
      tags:
        - Invoices
      summary: Get invoice details
      parameters:
        - name: invoice_id
          in: path
          description: Invoice id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/InvoiceDetailsOutput'
  '/invoices/{invoice_id}/details/{detail_id}':
    put:
      tags:
        - Invoices
      summary: Update invoice detail
      parameters:
        - name: invoice_id
          in: path
          description: Invoice id
          required: true
          schema:
            type: integer
        - name: detail_id
          in: path
          description: Detail id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/InvoiceDetailInput'
      responses:
        '201':
          description: No content
  '/invoices/{invoice_id}/details/{detail_id}/reject':
    post:
      tags:
        - Invoices
      summary: Reject invoice detail
      parameters:
        - name: invoice_id
          in: path
          description: Invoice id
          required: true
          schema:
            type: integer
        - name: detail_id
          in: path
          description: Detail id
          required: true
          schema:
            type: integer
      responses:
        '201':
          description: No content
  /invoices/approve:
    post:
      tags:
        - Invoices
      summary: Approve invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/InvoicesApproveInput'
      responses:
        '201':
          description: No content
  /invoices/attended/prepare:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvoicePrepareOutput'
      operationId: get-invoices-attended-prepare
      parameters:
        - schema:
            type: string
          in: query
          name: qr_code
          description: 'Qr code value '
        - schema:
            type: string
          in: query
          name: customer_id
  /invoices/reject:
    post:
      tags:
        - Invoices
      summary: Reject invoices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/InvoicesRejectInput'
      responses:
        '201':
          description: No content
  /terms:
    get:
      tags:
        - Terms
      summary: Get user terms and conditions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#components/schemas/UserTermsOutput'
components:
  schemas:
    ConfigurationOutput:
      type: object
      properties:
        articles:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
        price_levels:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
        fuelstations_settings:
          type: object
          properties:
            unattended_photo_values:
              type: array
              items:
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        payment_periodicities:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
    CustomersOutput:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        vat_number:
          type: string
        sdi_code:
          type: string
        pec:
          type: string
        address:
          type: string
        city:
          type: string
        province:
          type: string
        zip_code:
          type: string
        telephone:
          type: string
        email:
          type: string
        payment_periodicity_id:
          type: integer
        has_split_paymaent:
          type: boolean
        is_no_profit:
          type: boolean
    CustomersInput:
      type: object
      properties:
        name:
          type: string
        vat_number:
          type: string
        sdi_code:
          type: string
        pec:
          type: string
        address:
          type: string
        city:
          type: string
        province:
          type: string
        zip_code:
          type: string
        telephone:
          type: string
        email:
          type: string
        payment_periodicity_id:
          type: integer
        has_split_paymaent:
          type: boolean
        is_no_profit:
          type: boolean
    FuelstationsOutput:
      type: object
      properties:
        fuelstations:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
              address:
                type: string
              city:
                type: string
    FuelstationsSettingsOutput:
      type: object
      properties:
        settings:
          type: object
          properties:
            attended:
              type: object
              properties:
                auto_approval:
                  type: boolean
                is_ticket_mandatory:
                  type: boolean
                is_picture_mandatory:
                  type: boolean
                supply_auto_retrieve:
                  type: boolean
            unattended:
              type: object
              properties:
                auto_approval:
                  type: boolean
                is_ticket_mandatory:
                  type: boolean
                is_picture_mandatory:
                  type: integer
                  enum:
                    - 1
                    - 2
                    - 3
            pumps:
              type: integer
            articles:
              type: array
              items:
                properties:
                  code:
                    type: string
                  name:
                    type: string
    FuelstationSettingsInput:
      type: object
      properties:
        attended:
          type: object
          properties:
            auto_approval:
              type: boolean
            is_ticket_mandatory:
              type: boolean
            is_picture_mandatory:
              type: boolean
            supply_auto_retrieve:
              type: boolean
        unattended:
          type: object
          properties:
            auto_approval:
              type: boolean
            is_ticket_mandatory:
              type: boolean
            is_picture_mandatory:
              type: integer
              enum:
                - 1
                - 2
                - 3
    InvoicesSearchOutput:
      type: object
      properties:
        invoices:
          type: array
          items:
            properties:
              id:
                type: integer
              amount:
                type: number
              customer_name:
                type: string
              customer_vat_number:
                type: string
              date_time:
                type: string
                format: date-time
              is_immediate:
                type: boolean
              from_selfnet:
                type: boolean
              is_credit_note:
                type: boolean
    InvoicesApproveInput:
      type: object
      properties:
        invoices:
          type: array
          items:
            type: integer
    InvoicesRejectInput:
      type: object
      properties:
        invoices:
          type: array
          items:
            type: integer
    InvoiceDetailsOutput:
      type: object
      properties:
        details:
          type: array
          items:
            properties:
              user:
                type: string
              vehicle:
                type: object
                properties:
                  id:
                    type: integer
                  plate:
                    type: string
                  model:
                    type: string
              km:
                type: integer
              quantity:
                type: integer
              fuel_station:
                type: object
                properties:
                  full_address:
                    type: string
                  address:
                    type: string
                  city:
                    type: string
                  flag:
                    type: string
                  name:
                    type: string
                  phone_number:
                    type: string
                  cellphone_number:
                    type: string
              unit_of_measure:
                type: string
              payments:
                type: string
              ddt_number:
                type: string
              unit_price:
                type: number
              card_id:
                type: integer
              receipt_number:
                type: string
              total_amount:
                type: number
              id:
                type: integer
              invoice_id:
                type: integer
              article:
                type: object
                properties:
                  id:
                    type: integer
                  code:
                    type: string
                  description:
                    type: string
              transaction_timestamp:
                type: string
                format: date-time
    InvoiceDetailInput:
      type: object
      properties:
        payments:
          type: array
          items:
            properties:
              payment_method_code:
                type: string
                enum:
                  - MP02
                  - MP08
              amount:
                type: number
        vehicle_id:
          type: integer
        km:
          type: integer
        erog_id:
          type: integer
        unit_price:
          type: number
        article_code:
          type: integer
          format: int32
        receipt_number:
          type: string
        total_amount:
          type: number
        transaction_timestamp:
          type: string
          format: date-time
    InvoicePrepareOutput:
      title: InvoicePrepareOutput
      x-stoplight:
        id: e8omthn0lishq
      type: object
      properties:
        customer:
          type: object
          x-stoplight:
            id: 4ymu6r1bxiuwm
          properties:
            id:
              type: integer
              x-stoplight:
                id: mtksr6dgj02bg
            name:
              type: string
              x-stoplight:
                id: 4u43mg75tdpnp
        vehicles:
          type: object
          x-stoplight:
            id: v1dd2pvvljuwv
          properties:
            id:
              type: integer
              x-stoplight:
                id: liysnapjc5930
            name:
              type: string
              x-stoplight:
                id: w4t8gorr3lqn4
            plate:
              type: string
              x-stoplight:
                id: qczani13h2a12
            products:
              type: array
              x-stoplight:
                id: kzotdmj1pzcxm
              items:
                x-stoplight:
                  id: dwpxsy13w59sc
                type: string
    PricesOutput:
      type: object
      properties:
        prices:
          type: array
          items:
            properties:
              service_level:
                type: integer
              product_code:
                type: string
              price:
                type: number
    PricesInput:
      type: object
      properties:
        service_level:
          type: integer
        product_code:
          type: string
        price:
          type: number
    UserTermsOutput:
      type: object
      properties:
        app_privacy:
          type: boolean
        terms_and_conditions:
          type: boolean
        marketing:
          type: boolean
        third_parties:
          type: boolean
